name: MLflow CI Training

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 scikit-learn pandas numpy joblib

      - name: Run MLflow Project
        run: |
          cd MLProject
          # Menjalankan mlflow project di dalam folder MLProject
          mlflow run . --env-manager local

      - name: Upload mlruns artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns-artifact
          # Mengambil folder mlruns yang ada di dalam folder MLProject
          path: MLProject/mlruns